defaults:
  - attacks: attacks
  - datasets: datasets
  - models: models
  - override hydra/launcher: a100h100.yaml
  - _self_

hydra:
  mode: MULTIRUN
  run:
    dir: /nfs/staff-ssd/beyer/llm-quick-check/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}/
  job:
    chdir: true
  sweep:
    dir: /nfs/staff-ssd/beyer/llm-quick-check/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}/

name: testing
log_file: /nfs/staff-ssd/beyer/llm-quick-check/outputs/

# overrides for parallelism
attack_name: null
dataset_name: null
model_name: null